# Generated by Django 3.1.1 on 2020-10-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_alreadyliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alreadyLiked',
        ),
    ]
