# Generated by Django 3.1.1 on 2020-10-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_alreadyliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='followings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
