# Generated by Django 3.1.1 on 2020-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200929_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.TextField(default=''),
        ),
    ]
