# Generated by Django 3.1.1 on 2020-10-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_followinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
    ]
