# Generated by Django 3.1.1 on 2020-10-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_retweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_retweeted', models.TextField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postRetweetedBy', to='network.post')),
            ],
        ),
    ]
